name: ✨ Feature Request
description: Suggest a new feature or enhancement for eMark PDF Signer
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for your feature suggestion!
        We appreciate your input in making eMark PDF Signer better. Please provide as much detail as possible.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched [existing issues](https://github.com/trexolab-dev/emark-pdf-signer/issues) and this feature has not been requested.
          required: true
        - label: I have checked the [discussions](https://github.com/trexolab-dev/emark-pdf-signer/discussions) for related topics.
          required: false

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      description: What type of feature request is this?
      options:
        - New Feature - Something that doesn't exist yet
        - Enhancement - Improvement to an existing feature
        - UI/UX - Visual or usability improvement
        - Performance - Speed or efficiency improvement
        - Integration - Third-party tool or service integration
        - Accessibility - Accessibility improvement
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it clearly.
      placeholder: |
        I'm always frustrated when...
        Currently, there's no way to...
        It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        I would like eMark PDF Signer to...
        This could work by...
        The feature should allow users to...
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe how you would use this feature (optional but helpful).
      placeholder: |
        As a [type of user], I want to [goal] so that [benefit].

        Example: As a document signer, I want to preview my signature before applying it so that I can ensure it looks correct.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've tried...
        Other tools handle this by...
        A possible alternative could be...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have - Would be a welcome addition
        - Important - Would significantly improve my workflow
        - Critical - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, sketches, or examples from other tools.
      placeholder: Drag & drop images here or paste links to examples.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information or context about the feature request.
      placeholder: Include any relevant details, links to related issues, etc.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I am willing to help implement this feature.
        - label: I can provide more details or testing if needed.
